create table if not exists public.patients (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null,
  birth_date date,
  complaint text,
  created_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  patient_id bigint references public.patients(id) on delete cascade,
  doctor_name text not null,
  scheduled_at timestamptz not null,
  status text not null default 'terjadwal',
  created_at timestamptz not null default now()
);

create table if not exists public.bot_settings (
  id bigint primary key default 1 check (id = 1),
  enabled boolean not null default true,
  welcome_message text not null,
  updated_at timestamptz not null default now()
);

alter table public.patients enable row level security;
alter table public.appointments enable row level security;
alter table public.bot_settings enable row level security;

create policy "authenticated staff patients" on public.patients for all to authenticated using (true) with check (true);
create policy "authenticated staff appointments" on public.appointments for all to authenticated using (true) with check (true);
create policy "authenticated staff bot settings" on public.bot_settings for all to authenticated using (true) with check (true);

insert into public.bot_settings (id, enabled, welcome_message)
values (1, true, 'Terima kasih telah menghubungi Klinik Sehat. Admin kami akan segera membantu.')
on conflict (id) do nothing;
